### ISSUE TITLE
Format sortie par défaut GIF

### ISSUE THREAD

**Issue by Nania33** [darwikey/PFA-2D-3D#39]

**Comment by AlexandrePhilippi** [comment]
Quel est le problème ici ?

**Comment by Nania33** [comment]
Si on ne précise rien sous windows ça sort en PNG
Le 27 mars 2015 21:28, "Alexandre Philippi" <notifications@github.com> a
écrit :

**Comment by AlexandrePhilippi** [comment]
Je crois que c'est pareil sous linux, je vais voir ça !
